project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!exps/"

website:
  google-analytics: 
    tracking-id: "G-6C8LEPK16T"
    version: 4
    storage: cookies
    anonymize-ip: true

  title: "Raviteja Chukkapalli"
  image: mystuff/ravi-profile.png
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - notes.qmd
      - posts.qmd
      - projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



